### ISSUE TITLE
Cannot see font-awesome icons under login

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/mapknitter#690]
in the PR #633 a new `<link>` tag was added to `application.html.erb` for font-awesome:

https://github.com/publiclab/mapknitter/blob/5f25aa60243918b9d6a8f50a3db862358b25dafa/app/views/layouts/application.html.erb#L15

This makes it so that the icons no longer show up for this particular set of icons:

<img width="385" alt="Screen Shot 2019-06-13 at 1 29 40 AM" src="https://user-images.githubusercontent.com/41092741/59406059-c3ae0900-8d7a-11e9-85b8-f130911a3dad.png">

Removing this line brings the icons back

@stefannibrasil does this cause the same problem for you locally? Also was this meant for a font-awesome upgrade? I think we should update this dependency across the whole repo if were upgrading, and then link to the relative path in the href. Right now we are pulling 2 versions

**Comment by kaustubh-nair** [comment]
I believe this should fix it. https://github.com/publiclab/mapknitter/pull/669/commits/75c2fef36468ad17b0075085d389cd902b64d91a

**Comment by sashadev-sky** [comment]
hmm, since it's a small bug, could you maybe submit a quick PR just for that part? @kaustubh-nair. Then we can confirm its fixing it.

**Comment by kaustubh-nair** [comment]
@sashadev-sky I think it should be fixed now, since a6718529640a4469ba7e61443f4f23bf5ab657d2 got merged. Can you check again and confirm?

**Comment by sashadev-sky** [comment]
Yes its fixed! But I still see were pulling 2 different font-awesome packages into /public/lib that are version 4.2.0 and also pulling in another one via cdn that is version 5.8.2. I am going to open a PR to try getting it down to 1? Or is there a reason for this? @kaustubh-nair

**Comment by kaustubh-nair** [comment]
Hey @sashadev-sky I've tried looking into the cause of this.. I think this is happening because `image-sequencer` and `leaflet-distortableimage` have font-awesome as dependencies, which is causing a version mismatch. And maybe we should wait a bit to address this issue, since we are going to switch to yarn soon https://github.com/publiclab/mapknitter/pull/702/ 
Thanks!

**Comment by sashadev-sky** [comment]
@kaustubh-nair also in the process of removing font-awesome dependency in favor of svg sprites so we can use any icons we'd like in LDI! @jywarren

**Comment by sashadev-sky** [comment]
@kaustubh-nair font awesome has been removed from ldi! Is this issue fixed btw?

**Comment by kaustubh-nair** [comment]
We're using a new signup popup now right? I think @divyabaid16 implemented it?
Anyway I think the fontawesome issue was solved in Rails 4 upgrade

**Comment by sashadev-sky** [comment]
@kaustubh-nair yes closing this its stale and resolved!
