### ISSUE TITLE
rake db:migrate does not work

### ISSUE THREAD

**Issue by kaustubh-nair** [publiclab/mapknitter#703]
While running migrations for the first time, the migrations fail. A workaround for this is to use `rake db:setup` but it's a good idea to have clean migration files. 

```
== 20091016214109 CreateMaps: migrating =======================================
-- create_table(:maps)
rake aborted!
StandardError: An error has occurred, all later migrations canceled:

Mysql2::Error: BLOB, TEXT, GEOMETRY or JSON column 'styles' can't have a default value: CREATE TABLE `maps` (`id` int(11) auto_increment PRIMARY KEY, `name` varchar(255) DEFAULT '', `lat` decimal(20,10) DEFAULT 0, `lon` decimal(20,10) DEFAULT 0, `zoom` decimal DEFAULT 0.02, `version` int(11) DEFAULT 1, `password` varchar(255) DEFAULT '', `styles` text DEFAULT '', `created_at` datetime, `updated_at` datetime) ENGINE=InnoDB
/h
```

**Comment by alaxalves** [comment]
Is this on `main` branch?

**Comment by kaustubh-nair** [comment]
Yes its on the main branch

On Jun 17, 2019 6:26 PM, Álax de Carvalho Alves <notifications@github.com> wrote:

Is this on main branch?

**Comment by alaxalves** [comment]
Weird, so [this](https://github.com/publiclab/mapknitter/pull/685#issuecomment-502653067) might be coming from `main`.

**Comment by kaustubh-nair** [comment]
I think the problem here is with some specific migration file. Because here I can run `db:migrate` after deleting all the migrations. But it doesn't work on `rails-5`

**Comment by cesswairimu** [comment]
Which branch could I pull to replicate this? @alaxalves

**Comment by kaustubh-nair** [comment]
Hi @cesswairimu 
This is a problem on the main branch

**Comment by alaxalves** [comment]
Has this been fixed? @kaustubh-nair @cesswairimu

**Comment by jywarren** [comment]
Hi all, what's the latest with this? Thank you!

**Comment by gauravano** [comment]
Solved in https://github.com/publiclab/mapknitter/pull/891. @kaustubh-nair @alaxalves please verify. Thank you!

**Comment by kaustubh-nair** [comment]
Reopening this because I'm still facing this. The error is the same as mentioned above
I think there is something wrong with the create_maps migration? To reproduce it, drop database, create it, and run migrations
@publiclab/mapknitter-reviewers

**Comment by jywarren** [comment]
Aha, so @sashadev-sky was addressing this in #959 but actually we should not edit migrations in the past -- they're kind of like version tracking... and any migration already run on a live instance of the app should be considered permanent. Any changes should be added to a new migration - which is why they have timestamps. Does that make sense? So that means these changes to old migrations will cause trouble in any live instance of the app:

https://github.com/publiclab/mapknitter/pull/959/files#diff-1bb55a2824cab57e594057f2563e58a9L8

But! There is a solution. We can add/remove defaults and make changes using this syntax:

https://github.com/publiclab/plots2/blob/b6d5089c5ac3b80ef48481a6753f39b8dc0812ca/db/migrate/20180220180926_add_default_value_to_comment_status.rb#L3

So, instead of those migration changes, let's make all the necessary changes in a new migration with a new timestamp. Then people will be able to build a dev database from it with `rake db:setup`. 

Does that work for folks? Thank you!
